import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT


# ═══════════════════════════════════════════════
# SHARED STYLES & HELPERS
# ═══════════════════════════════════════════════

COPPER = colors.HexColor('#8B6F47')
COPPER_LIGHT = colors.HexColor('#F5F0E6')
COPPER_BG = colors.HexColor('#FDF8F0')
GREEN = colors.HexColor('#10b981')
RED = colors.HexColor('#ef4444')
BLUE = colors.HexColor('#6366f1')
AMBER = colors.HexColor('#f59e0b')
PURPLE = colors.HexColor('#8b5cf6')
CYAN = colors.HexColor('#06b6d4')
PINK = colors.HexColor('#ec4899')
DARK = colors.HexColor('#1a1a2e')
GRAY = colors.HexColor('#6b7280')
LIGHT_GRAY = colors.HexColor('#f3f4f6')


def get_base_styles():
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=COPPER,
        spaceAfter=4,
        leading=24,
    )
    subtitle_style = ParagraphStyle(
        'SubTitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=GRAY,
        spaceAfter=16,
    )
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=COPPER,
        spaceBefore=14,
        spaceAfter=8,
        borderWidth=0,
        borderPadding=0,
    )
    subsection_style = ParagraphStyle(
        'SubSectionHeading',
        parent=styles['Heading3'],
        fontSize=11,
        textColor=colors.HexColor('#4a3728'),
        spaceBefore=8,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.black,
        leading=14,
    )
    small_style = ParagraphStyle(
        'SmallText',
        parent=styles['Normal'],
        fontSize=8,
        textColor=GRAY,
        leading=11,
    )
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=7,
        textColor=colors.HexColor('#786432'),
        leading=10,
    )
    return styles, title_style, subtitle_style, section_style, subsection_style, body_style, small_style, disclaimer_style


def add_disclaimer(story, disclaimer_style):
    disclaimer_text = """<b>DISCLAIMER:</b> This report is generated by Finshala AI and is for educational purposes only. 
    It does not constitute financial, tax, or investment advice. Past performance is not indicative of future results. 
    Please consult a SEBI-registered investment advisor before making any financial decisions."""
    story.append(Paragraph(disclaimer_text, disclaimer_style))
    story.append(Spacer(1, 12))


def fmt_currency(n):
    """Format currency in Indian style."""
    if n is None:
        return "₹0"
    if not isinstance(n, (int, float)):
        try:
            n = float(n)
        except (ValueError, TypeError):
            return str(n)
    if abs(n) >= 10000000:
        return f"₹{n/10000000:.2f} Cr"
    elif abs(n) >= 100000:
        return f"₹{n/100000:.1f} L"
    elif abs(n) >= 1000:
        return f"₹{n/1000:.0f}K"
    else:
        return f"₹{int(n)}"


def fmt_pct(n):
    """Format percentage."""
    if n is None:
        return "0%"
    return f"{n:.1f}%"


def safe_get(data, *keys, default=0):
    """Safely navigate nested dicts."""
    current = data
    for key in keys:
        if isinstance(current, dict):
            current = current.get(key, default)
        else:
            return default
    return current if current is not None else default


def build_styled_table(data, col_widths, header=True, alternate_rows=True):
    """Build a consistently styled table."""
    styles_list = [
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
    ]
    if header and len(data) > 0:
        styles_list.extend([
            ('BACKGROUND', (0, 0), (-1, 0), COPPER_LIGHT),
            ('TEXTCOLOR', (0, 0), (-1, 0), COPPER),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('LINEBELOW', (0, 0), (-1, 0), 1, COPPER),
        ])
    if alternate_rows:
        for i in range(1 if header else 0, len(data)):
            if i % 2 == 0:
                styles_list.append(('BACKGROUND', (0, i), (-1, i), colors.HexColor('#FAFAFA')))
    styles_list.append(('LINEBELOW', (0, 0), (-1, -1), 0.3, colors.HexColor('#E5E7EB')))

    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle(styles_list))
    return t


def build_kv_table(rows, col_widths=(200, 240)):
    """Build a key-value table from [(label, value, bold?), ...] tuples."""
    ss = getSampleStyleSheet()
    table_data = []
    for row in rows:
        label = str(row[0])
        val = str(row[1])
        is_bold = row[2] if len(row) > 2 else False
        
        if is_bold:
            label_p = Paragraph(f"<b>{label}</b>", ss['Normal'])
            val_p = Paragraph(f"<b>{val}</b>", ss['Normal'])
        else:
            label_p = Paragraph(label, ss['Normal'])
            val_p = Paragraph(val, ss['Normal'])
        table_data.append([label_p, val_p])

    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (-1, -1), 0.4, colors.HexColor('#F0EBE0')),
    ]))
    return t


def add_footer(canvas_obj, doc):
    """Add footer to every page."""
    canvas_obj.saveState()
    canvas_obj.setFont('Helvetica', 7)
    canvas_obj.setFillColor(GRAY)
    page_num = canvas_obj.getPageNumber()
    canvas_obj.drawCentredString(
        A4[0] / 2, 15 * mm,
        f"Page {page_num}  |  Generated by Finshala AI  |  {datetime.now().strftime('%d %b %Y, %I:%M %p')}"
    )
    # Top copper line
    canvas_obj.setStrokeColor(COPPER)
    canvas_obj.setLineWidth(2)
    canvas_obj.line(14 * mm, A4[1] - 10 * mm, A4[0] - 14 * mm, A4[1] - 10 * mm)
    canvas_obj.restoreState()


# ═══════════════════════════════════════════════
# FIRE PDF REPORT — COMPREHENSIVE
# ═══════════════════════════════════════════════

def generate_fire_pdf(plan_data):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=36, leftMargin=36, topMargin=44, bottomMargin=44
    )
    story = []
    styles, title_style, subtitle_style, section_style, subsection_style, body_style, small_style, disclaimer_style = get_base_styles()

    pref = plan_data.get('preferred_variant', 'regular')
    variants = plan_data.get('variants', {})
    v = variants.get(pref, {})
    prof = plan_data.get('profile_summary', {})
    comparison = plan_data.get('comparison', {})

    # ── Title ──
    story.append(Paragraph("FINSHALA  |  FIRE Path Planner Report", title_style))
    story.append(Paragraph(
        f"Preferred Variant: {pref.upper()} FIRE  |  Age {safe_get(prof, 'current_age')}  |  "
        f"Generated on {datetime.now().strftime('%d %b %Y at %I:%M %p')}",
        subtitle_style
    ))
    add_disclaimer(story, disclaimer_style)

    # ══════════════════════════════════════════
    # 1. CURRENT PROFILE SNAPSHOT
    # ══════════════════════════════════════════
    story.append(Paragraph("1. Current Financial Profile Snapshot", section_style))
    prof_data = [
        ("Monthly Gross Income", fmt_currency(safe_get(prof, 'monthly_gross'))),
        ("Monthly Net Income (Post-Tax)", fmt_currency(safe_get(prof, 'monthly_net')), True),
        ("Monthly Expenses (Regular)", fmt_currency(safe_get(prof, 'monthly_expenses_regular'))),
        ("Monthly Expenses (Lean)", fmt_currency(safe_get(prof, 'monthly_expenses_lean'))),
        ("Monthly Expenses (Fat)", fmt_currency(safe_get(prof, 'monthly_expenses_fat'))),
        ("Monthly EMI Obligations", fmt_currency(safe_get(prof, 'monthly_emi'))),
        ("Investable Surplus", fmt_currency(safe_get(prof, 'current_investable_surplus')), True),
        ("Current Savings Rate", fmt_pct(safe_get(prof, 'savings_rate'))),
        ("Current Net Worth", fmt_currency(safe_get(prof, 'current_net_worth')), True),
        ("Life Expectancy (Assumed)", f"{safe_get(prof, 'life_expectancy', default=85)} years"),
    ]
    story.append(build_kv_table(prof_data))
    story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 2. FIRE TARGET — PREFERRED VARIANT DETAILS
    # ══════════════════════════════════════════
    config = v.get('config', {})
    story.append(Paragraph(f"2. {pref.upper()} FIRE — Target Analysis", section_style))
    target_data = [
        ("FIRE Variant", f"{config.get('emoji', '🔥')} {config.get('label', pref.upper() + ' FIRE')}", True),
        ("Description", str(config.get('description', ''))),
        ("Monthly Expenses for This Variant", fmt_currency(config.get('monthly_expenses', 0))),
        ("Target Retirement Age", f"{config.get('target_retirement_age', 'N/A')} years"),
        ("Safe Withdrawal Rate (SWR)", fmt_pct((config.get('swr', 0.035)) * 100)),
        ("", ""),
        ("Target FIRE Number", fmt_currency(v.get('fire_number', 0)), True),
        ("Projected FIRE Age", f"{v.get('fire_age', 'N/A')} years"),
        ("Years Until FIRE", f"{v.get('years_to_fire', 'N/A')} years"),
        ("Required Monthly SIP", fmt_currency(v.get('required_monthly_sip', 0)), True),
        ("Required Savings Rate", fmt_pct(v.get('savings_rate_needed', 0))),
        ("Monthly Expenses at FIRE", fmt_currency(v.get('monthly_expenses_at_fire', 0))),
        ("Annual Withdrawal at FIRE", fmt_currency(v.get('annual_withdrawal_at_fire', 0))),
        ("Feasibility", str(v.get('feasibility', 'Unknown')).upper(), True),
    ]
    story.append(build_kv_table(target_data))
    story.append(Spacer(1, 6))
    reason = v.get('feasibility_reason', '')
    if reason:
        story.append(Paragraph(f"<i>Feasibility Analysis:</i> {reason}", body_style))
    story.append(Spacer(1, 6))
    lnotes = config.get('lifestyle_notes', '')
    if lnotes:
        story.append(Paragraph(f"<i>Lifestyle Description:</i> {lnotes}", small_style))
    story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 3. ALL THREE VARIANT COMPARISON
    # ══════════════════════════════════════════
    story.append(Paragraph("3. Lean vs Regular vs Fat — Full Comparison", section_style))
    comp_table = [
        [
            Paragraph("<b>Metric</b>", styles['Normal']),
            Paragraph("<b>🌿 Lean FIRE</b>", styles['Normal']),
            Paragraph("<b>🔥 Regular FIRE</b>", styles['Normal']),
            Paragraph("<b>👑 Fat FIRE</b>", styles['Normal']),
        ]
    ]
    lean_v = variants.get('lean', {})
    reg_v = variants.get('regular', {})
    fat_v = variants.get('fat', {})

    rows_comp = [
        ("FIRE Number", 'fire_number', fmt_currency),
        ("FIRE Age", 'fire_age', lambda x: f"{x} years"),
        ("Years to FIRE", 'years_to_fire', lambda x: f"{x} years"),
        ("Required Monthly SIP", 'required_monthly_sip', fmt_currency),
        ("Savings Rate Needed", 'savings_rate_needed', lambda x: fmt_pct(x)),
        ("Monthly Expenses", None, None),  # special
        ("Expenses at FIRE", 'monthly_expenses_at_fire', fmt_currency),
        ("Annual Withdrawal", 'annual_withdrawal_at_fire', fmt_currency),
        ("Feasibility", 'feasibility', lambda x: str(x).upper()),
    ]
    for label, key, formatter in rows_comp:
        if key == 'monthly_expenses' or key is None:
            # special handling
            comp_table.append([
                Paragraph(label, styles['Normal']),
                Paragraph(fmt_currency(safe_get(lean_v, 'config', 'monthly_expenses')), styles['Normal']),
                Paragraph(fmt_currency(safe_get(reg_v, 'config', 'monthly_expenses')), styles['Normal']),
                Paragraph(fmt_currency(safe_get(fat_v, 'config', 'monthly_expenses')), styles['Normal']),
            ])
        else:
            comp_table.append([
                Paragraph(label, styles['Normal']),
                Paragraph(str(formatter(safe_get(lean_v, key))), styles['Normal']),
                Paragraph(str(formatter(safe_get(reg_v, key))), styles['Normal']),
                Paragraph(str(formatter(safe_get(fat_v, key))), styles['Normal']),
            ])

    story.append(build_styled_table(comp_table, col_widths=(120, 120, 120, 120)))
    story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 4. EMERGENCY FUND STRATEGY
    # ══════════════════════════════════════════
    story.append(Paragraph("4. Emergency Fund Strategy", section_style))
    em = v.get('emergency_fund_plan', {})
    em_data = [
        ("Current Emergency Fund", fmt_currency(em.get('current_fund', 0))),
        ("Target Emergency Fund", fmt_currency(em.get('target_fund', 0)), True),
        ("Shortfall / Gap", fmt_currency(em.get('gap', 0))),
        ("Monthly Contribution Needed", fmt_currency(em.get('monthly_contribution', 0))),
        ("Months to Fill Gap", f"{em.get('months_to_fill', 0)} months"),
        ("Recommended Deployment", str(em.get('where_to_park', 'Liquid Funds + FD')), True),
    ]
    story.append(build_kv_table(em_data))
    story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 5. SIP ALLOCATION PLAN
    # ══════════════════════════════════════════
    roadmap = v.get('monthly_roadmap', [])
    if roadmap:
        first_month = roadmap[0]
        sips = first_month.get('sip_allocations', [])
        if sips:
            story.append(Paragraph("5. Recommended SIP Allocation Plan", section_style))
            fund_labels = {
                'flexi_cap': 'Flexi Cap Fund', 'mid_cap': 'Mid Cap Fund', 'small_cap': 'Small Cap Fund',
                'elss': 'ELSS (Tax Saver)', 'large_cap': 'Large Cap Fund', 'debt': 'Debt Fund',
                'liquid': 'Liquid Fund', 'gold_etf': 'Gold ETF',
            }
            sip_table = [[
                Paragraph("<b>Goal / Theme</b>", styles['Normal']),
                Paragraph("<b>Fund Category</b>", styles['Normal']),
                Paragraph("<b>Monthly Amount</b>", styles['Normal']),
            ]]
            total_sip = 0
            for s in sips:
                amt = s.get('amount', 0)
                total_sip += amt
                sip_table.append([
                    Paragraph(s.get('goal_name', ''), styles['Normal']),
                    Paragraph(fund_labels.get(s.get('fund_type', ''), s.get('fund_type', '')), styles['Normal']),
                    Paragraph(fmt_currency(amt), styles['Normal']),
                ])
            sip_table.append([
                Paragraph("<b>TOTAL SIP</b>", styles['Normal']),
                Paragraph("", styles['Normal']),
                Paragraph(f"<b>{fmt_currency(total_sip)}</b>", styles['Normal']),
            ])
            story.append(build_styled_table(sip_table, col_widths=(130, 170, 120)))
            story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 6. FINANCIAL GOALS PROGRESS
    # ══════════════════════════════════════════
    if roadmap and roadmap[0].get('goal_progress'):
        goals = roadmap[0]['goal_progress']
        if goals:
            story.append(Paragraph("6. Financial Goals Tracker", section_style))
            goal_table = [[
                Paragraph("<b>Goal Name</b>", styles['Normal']),
                Paragraph("<b>Target Value</b>", styles['Normal']),
                Paragraph("<b>Current Corpus</b>", styles['Normal']),
                Paragraph("<b>SIP Needed</b>", styles['Normal']),
                Paragraph("<b>Status</b>", styles['Normal']),
                Paragraph("<b>Progress</b>", styles['Normal']),
            ]]
            for g in goals:
                status = "✓ On Track" if g.get('on_track') else "✗ Behind"
                goal_table.append([
                    Paragraph(str(g.get('goal_name', '')), styles['Normal']),
                    Paragraph(fmt_currency(g.get('target_future_value', 0)), styles['Normal']),
                    Paragraph(fmt_currency(g.get('current_corpus', 0)), styles['Normal']),
                    Paragraph(fmt_currency(g.get('monthly_sip_needed', 0)), styles['Normal']),
                    Paragraph(status, styles['Normal']),
                    Paragraph(fmt_pct(g.get('completion_pct', 0)), styles['Normal']),
                ])
            story.append(build_styled_table(goal_table, col_widths=(80, 80, 80, 80, 70, 60)))
            story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 7. MILESTONES TIMELINE
    # ══════════════════════════════════════════
    milestones = v.get('milestones', [])
    if milestones:
        story.append(Paragraph("7. Wealth Milestones Timeline", section_style))
        ms_table = [[
            Paragraph("<b>Date</b>", styles['Normal']),
            Paragraph("<b>Milestone</b>", styles['Normal']),
            Paragraph("<b>Net Worth</b>", styles['Normal']),
            Paragraph("<b>Type</b>", styles['Normal']),
        ]]
        for m in milestones[:12]:
            ms_table.append([
                Paragraph(str(m.get('target_date', '')), styles['Normal']),
                Paragraph(str(m.get('name', '')), styles['Normal']),
                Paragraph(fmt_currency(m.get('amount', 0)), styles['Normal']),
                Paragraph(str(m.get('type', '')).replace('_', ' ').title(), styles['Normal']),
            ])
        story.append(build_styled_table(ms_table, col_widths=(80, 200, 90, 80)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 8. ASSET ALLOCATION GLIDE PATH
    # ══════════════════════════════════════════
    glide_path = plan_data.get('glide_path', [])
    if glide_path:
        story.append(Paragraph("8. Asset Allocation Glide Path", section_style))
        story.append(Paragraph(
            "Your recommended asset allocation shifts as you age — more equity when young, more debt as you approach retirement.",
            small_style
        ))
        story.append(Spacer(1, 4))
        gp_table = [[
            Paragraph("<b>Age</b>", styles['Normal']),
            Paragraph("<b>Equity %</b>", styles['Normal']),
            Paragraph("<b>Debt %</b>", styles['Normal']),
            Paragraph("<b>Gold %</b>", styles['Normal']),
            Paragraph("<b>Real Estate %</b>", styles['Normal']),
        ]]
        for gp in glide_path:
            gp_table.append([
                Paragraph(f"Age {gp.get('age', '')}", styles['Normal']),
                Paragraph(f"{gp.get('equity_pct', 0)}%", styles['Normal']),
                Paragraph(f"{gp.get('debt_pct', 0)}%", styles['Normal']),
                Paragraph(f"{gp.get('gold_pct', 0)}%", styles['Normal']),
                Paragraph(f"{gp.get('real_estate_pct', 0)}%", styles['Normal']),
            ])
        story.append(build_styled_table(gp_table, col_widths=(80, 90, 90, 90, 90)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 9. TAX ANALYSIS
    # ══════════════════════════════════════════
    tax = plan_data.get('tax_analysis', {})
    if tax:
        story.append(Paragraph("9. Tax Regime Analysis", section_style))
        tax_data = [
            ("Old Regime Tax (Annual)", fmt_currency(tax.get('old_regime_tax', 0))),
            ("New Regime Tax (Annual)", fmt_currency(tax.get('new_regime_tax', 0))),
            ("Recommended Regime", str(tax.get('recommended_regime', '')).upper(), True),
            ("Potential Savings by Switching", fmt_currency(tax.get('annual_savings_by_switching', 0)), True),
            ("Effective Tax Rate", fmt_pct(tax.get('effective_tax_rate', 0))),
        ]
        story.append(build_kv_table(tax_data))
        story.append(Spacer(1, 8))

        moves = tax.get('tax_saving_moves', [])
        if moves:
            story.append(Paragraph("Tax-Saving Opportunities", subsection_style))
            move_table = [[
                Paragraph("<b>Section</b>", styles['Normal']),
                Paragraph("<b>Action Required</b>", styles['Normal']),
                Paragraph("<b>Used / Limit</b>", styles['Normal']),
                Paragraph("<b>Potential Saving</b>", styles['Normal']),
            ]]
            for m in moves:
                used = fmt_currency(m.get('current_utilization', 0))
                limit = fmt_currency(m.get('max_limit', 0))
                move_table.append([
                    Paragraph(str(m.get('section', '')), styles['Normal']),
                    Paragraph(str(m.get('action', '')), styles['Normal']),
                    Paragraph(f"{used} / {limit}" if m.get('max_limit', 0) > 0 else "—", styles['Normal']),
                    Paragraph(fmt_currency(m.get('potential_saving', 0)), styles['Normal']),
                ])
            story.append(build_styled_table(move_table, col_widths=(70, 170, 100, 100)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 10. INSURANCE GAPS
    # ══════════════════════════════════════════
    ins_gaps = plan_data.get('insurance_gaps', [])
    if ins_gaps:
        story.append(Paragraph("10. Insurance Gap Analysis", section_style))
        ins_table = [[
            Paragraph("<b>Type</b>", styles['Normal']),
            Paragraph("<b>Current Cover</b>", styles['Normal']),
            Paragraph("<b>Recommended</b>", styles['Normal']),
            Paragraph("<b>Gap</b>", styles['Normal']),
            Paragraph("<b>Est. Premium</b>", styles['Normal']),
            Paragraph("<b>Urgency</b>", styles['Normal']),
        ]]
        for ig in ins_gaps:
            ins_table.append([
                Paragraph(str(ig.get('type', '')).replace('_', ' ').title(), styles['Normal']),
                Paragraph(fmt_currency(ig.get('current_cover', 0)), styles['Normal']),
                Paragraph(fmt_currency(ig.get('recommended_cover', 0)), styles['Normal']),
                Paragraph(fmt_currency(ig.get('gap', 0)), styles['Normal']),
                Paragraph(fmt_currency(ig.get('estimated_premium', 0)) + "/yr", styles['Normal']),
                Paragraph(str(ig.get('urgency', '')).upper(), styles['Normal']),
            ])
        story.append(build_styled_table(ins_table, col_widths=(80, 70, 80, 70, 80, 60)))
        story.append(Spacer(1, 6))
        for ig in ins_gaps:
            reason = ig.get('reason', '')
            if reason:
                story.append(Paragraph(
                    f"• <b>{str(ig.get('type', '')).replace('_', ' ').title()}:</b> {reason}",
                    small_style
                ))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 11. YEARLY ROADMAP (First 20 Years)
    # ══════════════════════════════════════════
    yearly = [m for m in roadmap if m.get('month', 0) % 12 == 0][:20]
    if yearly:
        story.append(PageBreak())
        story.append(Paragraph(f"11. {pref.upper()} FIRE — Yearly Net Worth Roadmap", section_style))
        road_table = [[
            Paragraph("<b>Year</b>", styles['Normal']),
            Paragraph("<b>Age</b>", styles['Normal']),
            Paragraph("<b>Income</b>", styles['Normal']),
            Paragraph("<b>Expenses</b>", styles['Normal']),
            Paragraph("<b>Net Worth</b>", styles['Normal']),
            Paragraph("<b>FIRE %</b>", styles['Normal']),
            Paragraph("<b>Event</b>", styles['Normal']),
        ]]
        for m in yearly:
            pct_val = m.get('fire_progress_pct', 0)
            road_table.append([
                Paragraph(str(m.get('date', '')), styles['Normal']),
                Paragraph(str(m.get('age', '')), styles['Normal']),
                Paragraph(fmt_currency(m.get('net_income', 0)), styles['Normal']),
                Paragraph(fmt_currency(m.get('total_expenses', 0)), styles['Normal']),
                Paragraph(fmt_currency(m.get('total_net_worth', 0)), styles['Normal']),
                Paragraph(fmt_pct(pct_val), styles['Normal']),
                Paragraph(str(m.get('milestone_reached', '') or ''), styles['Normal']),
            ])
        story.append(build_styled_table(road_table, col_widths=(60, 35, 70, 70, 80, 50, 100)))

    # ── FOOTER NOTE ──
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This comprehensive FIRE report was generated by Finshala AI's Python Engine. "
        "All projections assume constant rates and are subject to market volatility.</i>",
        disclaimer_style
    ))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer.read()


# ═══════════════════════════════════════════════
# TAX PDF REPORT — COMPREHENSIVE
# ═══════════════════════════════════════════════

def generate_tax_pdf(tax_data):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=36, leftMargin=36, topMargin=44, bottomMargin=44
    )
    story = []
    styles, title_style, subtitle_style, section_style, subsection_style, body_style, small_style, disclaimer_style = get_base_styles()

    story.append(Paragraph("FINSHALA  |  Tax Wizard Report", title_style))
    story.append(Paragraph(
        f"FY 2024-25  |  AY 2025-26  |  Generated on {datetime.now().strftime('%d %b %Y at %I:%M %p')}",
        subtitle_style
    ))
    add_disclaimer(story, disclaimer_style)

    # ══════════════════════════════════════════
    # 1. REGIME COMPARISON & RECOMMENDATION
    # ══════════════════════════════════════════
    story.append(Paragraph("1. Tax Regime Comparison & AI Recommendation", section_style))
    old_regime = tax_data.get('old_regime', {})
    new_regime = tax_data.get('new_regime', {})
    rec = str(tax_data.get('recommended_regime', '')).upper()

    comp_data = [
        ("AI Recommended Regime", rec, True),
        ("", ""),
        ("Old Regime — Total Tax Liability", fmt_currency(old_regime.get('total_tax', 0))),
        ("Old Regime — Effective Tax Rate", fmt_pct(old_regime.get('effective_rate', 0))),
        ("Old Regime — Taxable Income", fmt_currency(old_regime.get('taxable_income', 0))),
        ("", ""),
        ("New Regime — Total Tax Liability", fmt_currency(new_regime.get('total_tax', 0))),
        ("New Regime — Effective Tax Rate", fmt_pct(new_regime.get('effective_rate', 0))),
        ("New Regime — Taxable Income", fmt_currency(new_regime.get('taxable_income', 0))),
        ("", ""),
        ("Annual Tax Savings by Switching", fmt_currency(
            tax_data.get('annual_savings_by_switching', tax_data.get('annual_savings', 0))
        ), True),
    ]
    story.append(build_kv_table(comp_data))
    story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 2. DEDUCTIONS BREAKDOWN (OLD REGIME)
    # ══════════════════════════════════════════
    db = old_regime.get('deduction_breakdown', [])
    if db:
        story.append(Paragraph("2. Deductions Utilization (Old Regime)", section_style))
        d_table = [[
            Paragraph("<b>Section / Category</b>", styles['Normal']),
            Paragraph("<b>Description</b>", styles['Normal']),
            Paragraph("<b>Claimed</b>", styles['Normal']),
            Paragraph("<b>Max Allowed</b>", styles['Normal']),
            Paragraph("<b>Utilization</b>", styles['Normal']),
        ]]
        for d in db:
            amount = d.get('amount', 0) or 0
            max_val = d.get('max', 0) or 0
            util_pct = fmt_pct((amount / max_val) * 100) if max_val > 0 else "—"
            d_table.append([
                Paragraph(f"Section {d.get('section', '')}", styles['Normal']),
                Paragraph(str(d.get('description', d.get('label', ''))), styles['Normal']),
                Paragraph(fmt_currency(amount), styles['Normal']),
                Paragraph(fmt_currency(max_val), styles['Normal']),
                Paragraph(util_pct, styles['Normal']),
            ])
        story.append(build_styled_table(d_table, col_widths=(80, 140, 80, 80, 60)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 3. TAX-SAVING MOVES / MISSED DEDUCTIONS
    # ══════════════════════════════════════════
    moves = tax_data.get('tax_saving_moves', [])
    missed = tax_data.get('missed_deductions', [])
    
    all_moves = moves + missed
    if all_moves:
        story.append(Paragraph("3. Prioritized Tax-Saving Actions", section_style))
        move_table = [[
            Paragraph("<b>Section</b>", styles['Normal']),
            Paragraph("<b>Action / Description</b>", styles['Normal']),
            Paragraph("<b>Potential Tax Saved</b>", styles['Normal']),
            Paragraph("<b>Regime</b>", styles['Normal']),
        ]]
        for m in moves:
            move_table.append([
                Paragraph(str(m.get('section', '')), styles['Normal']),
                Paragraph(str(m.get('action', m.get('description', ''))), styles['Normal']),
                Paragraph(fmt_currency(m.get('potential_saving', m.get('potential_tax_saving', 0))), styles['Normal']),
                Paragraph(str(m.get('regime', 'old')).upper(), styles['Normal']),
            ])
        for m in missed:
            move_table.append([
                Paragraph(str(m.get('section', '')), styles['Normal']),
                Paragraph(str(m.get('label', m.get('description', ''))), styles['Normal']),
                Paragraph(fmt_currency(m.get('potential_tax_saving', m.get('potential_saving', 0))), styles['Normal']),
                Paragraph("OLD", styles['Normal']),
            ])
        story.append(build_styled_table(move_table, col_widths=(70, 210, 100, 60)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 4. NEW REGIME SLAB BREAKDOWN
    # ══════════════════════════════════════════
    new_slabs = new_regime.get('slab_breakdown', [])
    if new_slabs:
        story.append(Paragraph("4. New Regime — Slab-wise Tax Breakdown", section_style))
        slab_table = [[
            Paragraph("<b>Income Slab</b>", styles['Normal']),
            Paragraph("<b>Rate</b>", styles['Normal']),
            Paragraph("<b>Tax Amount</b>", styles['Normal']),
        ]]
        for s in new_slabs:
            slab_table.append([
                Paragraph(str(s.get('slab', s.get('range', ''))), styles['Normal']),
                Paragraph(str(s.get('rate', '')), styles['Normal']),
                Paragraph(fmt_currency(s.get('tax', 0)), styles['Normal']),
            ])
        story.append(build_styled_table(slab_table, col_widths=(180, 100, 120)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 5. OLD REGIME SLAB BREAKDOWN
    # ══════════════════════════════════════════
    old_slabs = old_regime.get('slab_breakdown', [])
    if old_slabs:
        story.append(Paragraph("5. Old Regime — Slab-wise Tax Breakdown", section_style))
        slab_table = [[
            Paragraph("<b>Income Slab</b>", styles['Normal']),
            Paragraph("<b>Rate</b>", styles['Normal']),
            Paragraph("<b>Tax Amount</b>", styles['Normal']),
        ]]
        for s in old_slabs:
            slab_table.append([
                Paragraph(str(s.get('slab', s.get('range', ''))), styles['Normal']),
                Paragraph(str(s.get('rate', '')), styles['Normal']),
                Paragraph(fmt_currency(s.get('tax', 0)), styles['Normal']),
            ])
        story.append(build_styled_table(slab_table, col_widths=(180, 100, 120)))
        story.append(Spacer(1, 12))

    # ── AI EXPLANATION ──
    ai_text = tax_data.get('ai_explanation', '') or tax_data.get('ai_analysis', '')
    if ai_text:
        story.append(Paragraph("AI Tax Analysis", section_style))
        story.append(Paragraph(str(ai_text), body_style))

    # ── FOOTER NOTE ──
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This tax analysis is for the financial year 2024-25. Tax laws and rates may change. "
        "Always verify with your CA before filing returns.</i>",
        disclaimer_style
    ))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer.read()


# ═══════════════════════════════════════════════
# HEALTH SCORE PDF REPORT — COMPREHENSIVE
# ═══════════════════════════════════════════════

def generate_health_pdf(health_data):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=36, leftMargin=36, topMargin=44, bottomMargin=44
    )
    story = []
    styles, title_style, subtitle_style, section_style, subsection_style, body_style, small_style, disclaimer_style = get_base_styles()

    ov_score = health_data.get('overall_score', 0)
    ov_grade = health_data.get('overall_grade', 'N/A')

    story.append(Paragraph("FINSHALA  |  Comprehensive Money Health Report", title_style))
    story.append(Paragraph(
        f"Score: {ov_score}/900 (Grade {ov_grade})  |  Generated on {datetime.now().strftime('%d %b %Y at %I:%M %p')}",
        subtitle_style
    ))
    add_disclaimer(story, disclaimer_style)

    # ══════════════════════════════════════════
    # 1. HIGH-LEVEL SUMMARY
    # ══════════════════════════════════════════
    story.append(Paragraph("1. High-Level Financial Health Summary", section_style))
    meta = health_data.get('meta', {})
    ov_data = [
        ("Finshala Money Health Score", f"{ov_score} / 900", True),
        ("Overall Grade", str(ov_grade), True),
        ("Health Status", str(health_data.get('overall_status', 'Unknown')).title()),
        ("", ""),
        ("Monthly Gross Income", fmt_currency(meta.get('monthly_income', meta.get('gross_monthly', 0)))),
        ("Monthly Net Income", fmt_currency(meta.get('net_monthly', 0))),
        ("Monthly Expenses", fmt_currency(meta.get('monthly_expenses', 0))),
        ("Total Net Worth", fmt_currency(meta.get('net_worth', 0)), True),
        ("Total Assets", fmt_currency(meta.get('total_assets', 0))),
        ("Total Liabilities", fmt_currency(meta.get('total_liabilities', 0))),
        ("Savings Rate", fmt_pct(meta.get('savings_rate', 0))),
    ]
    story.append(build_kv_table(ov_data))
    story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 2. 6-DIMENSION BREAKDOWN
    # ══════════════════════════════════════════
    dims = health_data.get('dimension_list', [])
    if dims:
        story.append(Paragraph("2. Financial Health — 6-Dimension Breakdown", section_style))
        dim_table = [[
            Paragraph("<b>Dimension</b>", styles['Normal']),
            Paragraph("<b>Score</b>", styles['Normal']),
            Paragraph("<b>Grade</b>", styles['Normal']),
            Paragraph("<b>Status</b>", styles['Normal']),
            Paragraph("<b>Weight</b>", styles['Normal']),
        ]]
        for d in dims:
            dim_table.append([
                Paragraph(str(d.get('name', '')), styles['Normal']),
                Paragraph(f"{d.get('score', 0)} / 100", styles['Normal']),
                Paragraph(f"Grade {d.get('grade', '')}", styles['Normal']),
                Paragraph(str(d.get('status', '')).title(), styles['Normal']),
                Paragraph(f"{d.get('weight', '')}%", styles['Normal']),
            ])
        story.append(build_styled_table(dim_table, col_widths=(130, 70, 70, 90, 60)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 3. DETAILED DIAGNOSTICS PER DIMENSION
    # ══════════════════════════════════════════
    if dims:
        story.append(Paragraph("3. Detailed Diagnostics & Insights", section_style))
        for d in dims:
            name = d.get('name', '')
            score = d.get('score', 0)
            grade = d.get('grade', '')
            insight = d.get('insight', 'No specific finding.')
            
            story.append(Paragraph(
                f"<b>{name}</b>  —  {score}/100 (Grade {grade})",
                subsection_style
            ))
            story.append(Paragraph(str(insight), body_style))
            
            # Sub-metrics if available
            sub_metrics = d.get('sub_metrics', d.get('metrics', []))
            if sub_metrics and isinstance(sub_metrics, list):
                for sm in sub_metrics:
                    if isinstance(sm, dict):
                        sm_name = sm.get('name', sm.get('label', ''))
                        sm_val = sm.get('value', sm.get('score', ''))
                        sm_status = sm.get('status', '')
                        story.append(Paragraph(
                            f"  • <b>{sm_name}:</b> {sm_val} {('(' + sm_status + ')') if sm_status else ''}",
                            small_style
                        ))
            
            # Vulnerabilities
            vulns = d.get('vulnerabilities', [])
            if vulns:
                for vul in vulns:
                    if isinstance(vul, str):
                        story.append(Paragraph(f"  ⚠ {vul}", small_style))
                    elif isinstance(vul, dict):
                        story.append(Paragraph(
                            f"  ⚠ {vul.get('description', vul.get('issue', ''))}",
                            small_style
                        ))
            
            story.append(Spacer(1, 6))

    # ══════════════════════════════════════════
    # 4. PRIORITY ACTIONS
    # ══════════════════════════════════════════
    actions = health_data.get('top_actions', [])
    if actions:
        story.append(Paragraph("4. Recommended Priority Actions", section_style))
        act_table = [[
            Paragraph("<b>#</b>", styles['Normal']),
            Paragraph("<b>Priority</b>", styles['Normal']),
            Paragraph("<b>Dimension</b>", styles['Normal']),
            Paragraph("<b>Specific Action to Take</b>", styles['Normal']),
        ]]
        for i, a in enumerate(actions[:10]):
            act_table.append([
                Paragraph(str(i + 1), styles['Normal']),
                Paragraph(str(a.get('priority', '')).upper(), styles['Normal']),
                Paragraph(str(a.get('dimension', '')), styles['Normal']),
                Paragraph(str(a.get('action', '')), styles['Normal']),
            ])
        story.append(build_styled_table(act_table, col_widths=(25, 65, 100, 250)))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 5. STRENGTHS
    # ══════════════════════════════════════════
    strengths = health_data.get('strengths', [])
    if strengths:
        story.append(Paragraph("5. Financial Strengths", section_style))
        for s in strengths:
            if isinstance(s, str):
                story.append(Paragraph(f"✅ {s}", body_style))
            elif isinstance(s, dict):
                story.append(Paragraph(
                    f"✅ <b>{s.get('dimension', '')}:</b> {s.get('description', s.get('strength', ''))}",
                    body_style
                ))
        story.append(Spacer(1, 12))

    # ══════════════════════════════════════════
    # 6. VULNERABILITIES / RISK FLAGS
    # ══════════════════════════════════════════
    vulns = health_data.get('vulnerabilities', health_data.get('risk_flags', []))
    if vulns:
        story.append(Paragraph("6. Vulnerabilities & Risk Flags", section_style))
        for v_item in vulns:
            if isinstance(v_item, str):
                story.append(Paragraph(f"⚠️ {v_item}", body_style))
            elif isinstance(v_item, dict):
                story.append(Paragraph(
                    f"⚠️ <b>{v_item.get('dimension', '')}:</b> {v_item.get('description', v_item.get('issue', ''))}",
                    body_style
                ))
        story.append(Spacer(1, 12))

    # ── AI ADVICE ──
    ai_text = health_data.get('ai_advice', '') or health_data.get('ai_analysis', '')
    if ai_text:
        story.append(Paragraph("AI Financial Advice", section_style))
        story.append(Paragraph(str(ai_text), body_style))

    # ── FOOTER NOTE ──
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>Your Money Health Score is calculated across 6 dimensions — Savings, Debt, Protection, Tax Efficiency, "
        "Investment Quality, and Emergency Preparedness. Scores update as your financial profile changes.</i>",
        disclaimer_style
    ))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer.read()
