// ═══════════════════════════════════════════════
// PDF REPORT GENERATOR — Finshala
// Downloads comprehensive PDFs from Python backend
// Falls back to client-side jsPDF if backend unavailable
// ═══════════════════════════════════════════════

declare const jspdf: any;

function loadJsPDF(): Promise<any> {
  if ((window as any).jspdf) return Promise.resolve((window as any).jspdf);
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js';
    script.onload = () => resolve((window as any).jspdf);
    script.onerror = () => reject(new Error('Failed to load jsPDF'));
    document.head.appendChild(script);
  });
}

// ── Safe PDF download helper ──
// Converts blob to base64 data-URI to avoid "unsafe" blob:http warnings
function safeDownloadPDF(blob: Blob, filename: string) {
  const reader = new FileReader();
  reader.onloadend = () => {
    const a = document.createElement('a');
    a.href = reader.result as string;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    // Small timeout to ensure download starts
    setTimeout(() => {
      document.body.removeChild(a);
    }, 200);
  };
  reader.readAsDataURL(blob);
}

// ── Shared helpers ──

function addHeader(doc: any, title: string, subtitle: string) {
  // Brand header
  doc.setFillColor(139, 111, 71); // Copper
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FINSHALA', 14, 12);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 14, 20);
  doc.setFontSize(8);
  doc.text(subtitle, 14, 25);
  doc.setTextColor(0, 0, 0);
}

function addDisclaimer(doc: any, y: number): number {
  doc.setFillColor(255, 248, 230);
  doc.rect(14, y, 182, 14, 'F');
  doc.setDrawColor(184, 134, 11);
  doc.rect(14, y, 182, 14, 'S');
  doc.setFontSize(7);
  doc.setTextColor(120, 100, 50);
  doc.text('DISCLAIMER: This report is for educational purposes only. Not financial, tax, or investment advice.', 18, y + 5);
  doc.text('Consult a SEBI-registered advisor before making financial decisions.', 18, y + 10);
  doc.setTextColor(0, 0, 0);
  return y + 18;
}

function addSection(doc: any, title: string, y: number): number {
  if (y > 260) { doc.addPage(); y = 20; }
  doc.setFillColor(245, 240, 230);
  doc.rect(14, y, 182, 8, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(139, 111, 71);
  doc.text(title, 18, y + 5.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  return y + 12;
}

function addRow(doc: any, label: string, value: string, y: number, bold = false): number {
  if (y > 270) { doc.addPage(); y = 20; }
  doc.setFontSize(9);
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.text(label, 18, y);
  doc.text(value, 180, y, { align: 'right' });
  return y + 5.5;
}

function addParagraph(doc: any, text: string, y: number, maxWidth = 170): number {
  if (y > 260) { doc.addPage(); y = 20; }
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, 18, y);
  return y + lines.length * 4 + 2;
}

function addFooter(doc: any) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount} | Generated by Finshala AI | ${new Date().toLocaleDateString('en-IN')}`, 105, 290, { align: 'center' });
  }
}

const fmt = (n: number) => n >= 10000000 ? `Rs ${(n/10000000).toFixed(2)}Cr` : n >= 100000 ? `Rs ${(n/100000).toFixed(1)}L` : `Rs ${(n/1000).toFixed(0)}K`;

// ═══════════════════════════════════════════════
// FIRE PLANNER PDF
// ═══════════════════════════════════════════════

export async function generateFirePDF(plan: any, aiRoadmap?: string): Promise<void> {
  try {
    const response = await fetch('/api/generate-report/fire', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(plan),
    });
    if (!response.ok) throw new Error('API failed');
    const blob = await response.blob();
    safeDownloadPDF(blob, 'Finshala_FIRE_Report.pdf');
    return;
  } catch (error) {
    console.warn("Python PDF API failed, falling back to local JS generation", error);
  }

  const { jsPDF } = await loadJsPDF();
  const doc = new jsPDF();
  const v = plan.variants[plan.preferred_variant];

  addHeader(doc, 'FIRE Planner Report', `Generated for Age ${plan.profile_summary.current_age} | ${new Date().toLocaleDateString('en-IN')}`);
  let y = 35;

  y = addDisclaimer(doc, y);

  // Summary
  y = addSection(doc, 'FIRE Summary', y);
  y = addRow(doc, 'Preferred Variant', plan.preferred_variant.toUpperCase() + ' FIRE', y, true);
  y = addRow(doc, 'FIRE Number', fmt(v.fire_number), y);
  y = addRow(doc, 'FIRE Age', `${v.fire_age} years old`, y);
  y = addRow(doc, 'Years to FIRE', `${v.years_to_fire} years`, y);
  y = addRow(doc, 'Current Net Worth', fmt(plan.current_net_worth), y);
  y = addRow(doc, 'Required Monthly SIP', fmt(v.required_monthly_sip), y);
  y = addRow(doc, 'Savings Rate Needed', `${v.savings_rate_needed}%`, y);
  y = addRow(doc, 'Feasibility', v.feasibility.toUpperCase(), y, true);
  y += 4;

  // All 3 variants comparison
  y = addSection(doc, 'Variant Comparison', y);
  (['lean', 'regular', 'fat'] as const).forEach((variant) => {
    const d = plan.variants[variant];
    y = addRow(doc, `${variant.toUpperCase()} FIRE`, `${fmt(d.fire_number)} by age ${d.fire_age} (${d.years_to_fire}yr) | SIP: ${fmt(d.required_monthly_sip)}/mo`, y);
  });
  y += 4;

  // Emergency Fund
  if (v.emergency_fund_plan) {
    y = addSection(doc, 'Emergency Fund', y);
    y = addRow(doc, 'Target Fund', fmt(v.emergency_fund_plan.target_fund), y);
    y = addRow(doc, 'Current Fund', fmt(v.emergency_fund_plan.current_fund), y);
    y = addRow(doc, 'Gap', fmt(v.emergency_fund_plan.gap), y);
    y = addRow(doc, 'Monthly Contribution', fmt(v.emergency_fund_plan.monthly_contribution), y);
    y += 4;
  }

  // Milestones
  if (v.milestones?.length) {
    y = addSection(doc, 'Key Milestones', y);
    v.milestones.slice(0, 8).forEach((m: any) => {
      y = addRow(doc, m.name, `${fmt(m.amount)} by ${m.target_date}`, y);
    });
    y += 4;
  }

  // SIP Allocations
  const sips = v.monthly_roadmap?.[0]?.sip_allocations;
  if (sips?.length) {
    y = addSection(doc, 'SIP Allocation Plan', y);
    sips.forEach((s: any) => {
      y = addRow(doc, `${s.goal_name} — ${s.fund_type.replace(/_/g, ' ')}`, fmt(s.amount), y);
    });
    y += 4;
  }

  // AI Roadmap
  if (aiRoadmap) {
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSection(doc, 'AI-Generated Roadmap', y);
    y = addParagraph(doc, aiRoadmap, y);
  }

  addFooter(doc);
  doc.save('Finshala_FIRE_Report.pdf');
}

// ═══════════════════════════════════════════════
// TAX WIZARD PDF
// ═══════════════════════════════════════════════

export async function generateTaxPDF(data: any, aiExplanation?: string): Promise<void> {
  try {
    const response = await fetch('/api/generate-report/tax', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!response.ok) throw new Error('API failed');
    const blob = await response.blob();
    safeDownloadPDF(blob, 'Finshala_Tax_Report.pdf');
    return;
  } catch (error) {
    console.warn("Python PDF API failed, falling back to local JS generation", error);
  }

  const { jsPDF } = await loadJsPDF();
  const doc = new jsPDF();

  addHeader(doc, 'Tax Wizard Report', `FY 2024-25 | AY 2025-26 | ${new Date().toLocaleDateString('en-IN')}`);
  let y = 35;

  y = addDisclaimer(doc, y);

  // Regime comparison
  y = addSection(doc, 'Regime Comparison', y);
  y = addRow(doc, 'Recommended Regime', data.recommended_regime.toUpperCase(), y, true);
  y = addRow(doc, 'Old Regime Tax', fmt(data.old_regime.total_tax), y);
  y = addRow(doc, 'New Regime Tax', fmt(data.new_regime.total_tax), y);
  y = addRow(doc, 'Annual Savings (by switching)', fmt(data.annual_savings || data.annual_savings_by_switching || 0), y, true);
  y = addRow(doc, 'Old Effective Rate', `${data.old_regime.effective_rate}%`, y);
  y = addRow(doc, 'New Effective Rate', `${data.new_regime.effective_rate}%`, y);
  y += 4;

  // Deductions (old regime)
  y = addSection(doc, 'Deductions Used (Old Regime)', y);
  data.old_regime.deduction_breakdown?.forEach((d: any) => {
    if (d.amount > 0) {
      y = addRow(doc, `Section ${d.section}`, `${fmt(d.amount)} / ${fmt(d.max)}`, y);
    }
  });
  y += 4;

  // Tax-saving moves
  if (data.tax_saving_moves?.length) {
    y = addSection(doc, 'Tax-Saving Opportunities', y);
    data.tax_saving_moves.forEach((m: any) => {
      y = addRow(doc, `${m.section}: ${m.action || m.description}`, `Save ${fmt(m.potential_saving || m.potential_tax_saving || 0)}`, y);
    });
    y += 4;
  }

  // Missed deductions
  if (data.missed_deductions?.length) {
    y = addSection(doc, 'Missed Deductions', y);
    data.missed_deductions.forEach((m: any) => {
      y = addRow(doc, `${m.section}: ${m.label}`, `Save up to ${fmt(m.potential_tax_saving)}`, y);
    });
    y += 4;
  }

  // AI explanation
  if (aiExplanation) {
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSection(doc, 'AI Regime Analysis', y);
    y = addParagraph(doc, aiExplanation, y);
  }

  addFooter(doc);
  doc.save('Finshala_Tax_Report.pdf');
}

// ═══════════════════════════════════════════════
// MONEY HEALTH SCORE PDF
// ═══════════════════════════════════════════════

export async function generateHealthPDF(data: any, aiAdvice?: string): Promise<void> {
  try {
    const response = await fetch('/api/generate-report/health', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!response.ok) throw new Error('API failed');
    const blob = await response.blob();
    safeDownloadPDF(blob, 'Finshala_Health_Score_Report.pdf');
    return;
  } catch (error) {
    console.warn("Python PDF API failed, falling back to local JS generation", error);
  }

  const { jsPDF } = await loadJsPDF();
  const doc = new jsPDF();

  addHeader(doc, 'Money Health Score Report', `Score: ${data.overall_score}/900 (Grade ${data.overall_grade}) | ${new Date().toLocaleDateString('en-IN')}`);
  let y = 35;

  y = addDisclaimer(doc, y);

  // Overall
  y = addSection(doc, 'Overall Score', y);
  y = addRow(doc, 'Score', `${data.overall_score} / 900`, y, true);
  y = addRow(doc, 'Grade', data.overall_grade, y, true);
  y = addRow(doc, 'Status', (data.overall_status || 'Unknown'), y);
  y = addRow(doc, 'Monthly Income', fmt(data.meta?.monthly_income || 0), y);
  y = addRow(doc, 'Net Worth', fmt(data.meta?.net_worth || 0), y);
  y += 4;

  // Dimensions
  y = addSection(doc, '6-Dimension Breakdown', y);
  data.dimension_list?.forEach((dim: any) => {
    y = addRow(doc, `${dim.name}`, `${dim.score}/100 (Grade ${dim.grade})`, y);
    if (y > 260) { doc.addPage(); y = 20; }
  });
  y += 4;

  // Detailed Diagnostics
  if (data.dimension_list?.length) {
    y = addSection(doc, 'Detailed Diagnostics', y);
    data.dimension_list.forEach((dim: any) => {
      y = addRow(doc, dim.name, dim.insight || 'No specific finding.', y);
      if (y > 260) { doc.addPage(); y = 20; }
    });
    y += 4;
  }

  // Top Actions
  if (data.top_actions?.length) {
    y = addSection(doc, 'Priority Actions', y);
    data.top_actions.slice(0, 8).forEach((a: any, i: number) => {
      y = addRow(doc, `${i + 1}. [${a.priority?.toUpperCase() || ''}] ${a.dimension || ''}`, a.action, y);
      if (y > 260) { doc.addPage(); y = 20; }
    });
    y += 4;
  }

  // Strengths
  if (data.strengths?.length) {
    y = addSection(doc, 'Financial Strengths', y);
    data.strengths.forEach((s: any) => {
      const text = typeof s === 'string' ? s : `${s.dimension}: ${s.description || s.strength}`;
      y = addRow(doc, `✅ ${text}`, '', y);
      if (y > 260) { doc.addPage(); y = 20; }
    });
    y += 4;
  }

  // AI advice
  if (aiAdvice) {
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSection(doc, 'AI Financial Advice', y);
    y = addParagraph(doc, aiAdvice, y);
  }

  addFooter(doc);
  doc.save('Finshala_Health_Score_Report.pdf');
}
